services:
  stable-diffusion:
    build: .
      #ports:
      #  - 8081:80
    volumes:
      - ./app:/app
      - .cache/huggingface:/root/.cache/huggingface
    working_dir: /app
    tty: true

      #environment:
      #  - TOKEN_ISSUER=http://cognito:80
      #  - USER_POOL_FILE_NAME=/app/pool.json
